### PR TITLE
Update css dependency that fixes a security issue

### PR DESCRIPTION
**Pull request by JulienPradet**
I'm using `html-react-parser` and Snyk tells me that through `style-to-object`, it depends on a version of `reworkcss/css` that actually has a security risk.
Hopefully, [it has been fixed](https://github.com/reworkcss/css/commit/e91bb74051469d9c521b1b966460b44877e961fb). So here is a PR to propagate the fix in `style-to-object`.
Could you also do a release on `html-react-parser` once `style-to-object` will be released?

I'm not used to your commit message style. Is it something to do automatic changelogs? How should I amend mine?

By the way, I was wondering what was the reason behind choosing `reworkcss/css` for the CSS parser? It seems to be abandonned in favor of PostCSS. Even though, I guess PostCSS would be too big as a dependency, maybe there are lighter alternatives?

Anyway, thanks a lot for your work! It's great!

### CODE REVIEW

**Comment by remarkablemark** [comment]
Thanks for the PR @JulienPradet. I'll make a release and then update `html-react-parser` once the message is amended.

- [ ] Amend commit message and update branch:
  ```
  git commit --amend -m "fix(package): upgrade css@2.2.3 which resolves security vulnerability"
  git push origin master --force
  ```

Fyi, I'm using [standard-version](https://github.com/conventional-changelog/standard-version) which follows [conventional commits](https://conventionalcommits.org) for releasing (determines which version to bump and helps with changelog generation).

Like you mentioned, I chose `rework/css` over `postcss` due to the library size since `html-react-parser`can be used isomorphically. I'm open to evaluating alternatives that performs well and is light when bundled on the client.

**Comment by JulienPradet** [comment]
Thank you for the additional pieces of information. I've updated the commit.

I'll come up with a PR for the CSS parser, brb :)

**Comment by JulienPradet** [comment]
Nevermind about the PR. I thought that I could do something with [CSSStyleDeclaration](https://drafts.csswg.org/cssom/#the-cssstyledeclaration-interface), but it transforms the values of the CSS properties (`#f00` becomes `rgb(255,0,0)`). It would break SSR.
To fix this, we could use a node implementation of CSSStyleDeclaration. But the only one that I found doesn't feel safe at all (https://github.com/chad3814/CSSStyleDeclaration).

**Comment by remarkablemark** [comment]
No problem. We can investigate other viable solutions or we could always write our own. Thanks for the attempt.

**Comment by remarkablemark** [comment]
@JulienPradet I have released `style-to-object@0.2.1` and `html-react-parser@0.4.5` with your fix

**Pull request merged**
