### PR TITLE
feat: add typescript support

### PR DESCRIPTION
**Pull request by moonrailgun**

### CODE REVIEW

**Comment by moonrailgun** [comment]
DONE! add dtslint for index.d.ts

append a simple tsconfig and a recommend tslint 

NOTICE: i have no idea to append dtslint into lint-staged
`lint-staged` will add absolute path of changed file after command but `dtslint` only receive a relative path. i dont know how to fix it.

**Comment by moonrailgun** [comment]
well

**Comment by remarkablemark** [comment]
> well

I think you didn't finish your train of thought? If everything's good, I plan to merge this PR.

**Comment by moonrailgun** [comment]
Everythink is been ok. except `lint-staged`.

Expect your merge, and hope to release it as quickly as possible then i can enjoy it with offical support

think for your codereview.

**Comment by remarkablemark** [comment]
[`style-to-object@0.3.0`](https://github.com/remarkablemark/style-to-object/releases/tag/v0.3.0) has been released and published:

```sh
# update with npm
npm i -S style-to-object@0.3.0

# or with yarn
yarn add style-to-object@0.3.0
```

**Pull request merged**
